CREATE TABLE users
(
    id            NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR2(100)                                  NOT NULL,
    password      VARCHAR2(255),
    name          VARCHAR2(100)                                  NOT NULL,
    nickname      VARCHAR2(100)                                  NOT NULL,
    provider      VARCHAR2(20)                                   NOT NULL,
    role          VARCHAR2(20)                                   NOT NULL,
    contact_email VARCHAR2(100)                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);
