CREATE TABLE users
(
    id               NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    email            VARCHAR2(100)                                  NOT NULL,
    password         VARCHAR2(255)                                  NOT NULL,
    name             VARCHAR2(100)                                  NOT NULL,
    nickname         VARCHAR2(100)                                  NOT NULL,
    role             VARCHAR2(20)                                   NOT NULL,
    profile_name     VARCHAR2(100),
    origin_file_name VARCHAR2(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE INDEX idx_users_nickname ON users (nickname);
