apiVersion: v1
kind: Service
metadata:
  name: blaybus-app-service
  namespace: blaybus
spec:
  selector:
    app: blaybus-app
  ports:
    - port: 80 # 서비스 포트
      targetPort: 8080 # 컨테이너 포트
  type: ClusterIP
